### ISSUE TITLE
Add Algolia DocSearch

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline.ai#9]

**Comment by mattbr0wn** [comment]
https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by jontyk** [comment]
Notes:
This requires application:
- https://docsearch.algolia.com/docs/who-can-apply/
- https://docsearch.algolia.com/apply/
We should only pick this and apply when documentation is ready as that is when the site will be indexed by Algolia.

**Comment by jontyk** [comment]
Applied for Algolia Docsearch
